### ISSUE TITLE
camera freeze on ipad without GPS / no error displayed

### ISSUE THREAD

**Issue by pikilipita** [mozilla-mobile/webxr-ios#56] opened 2018-02-06 12:49 UTC
I've seen on closed issues that the app requires location services.

When trying on ipad model 2017 wifi only ( no simcard, no GPS ) the camera view just freeze when opening any of the examples.
I think an error message about location services not being accessible/present on the device would really help users to figure out why the examples are not working.

Will webXR work in future without location services?

**Comment by blairmacintyre** [comment] 2018-02-06 13:54
We'll look into this.  I don't think any of us have iPads without GPS (but I'm not sure).  However, we were just looking removing the need for location access entirely, so perhaps this will get fixed when we do that.

Right now, we are requesting that ARKit align it's coordinate system with EUS, which very likely requires location.  But, we'll see.  Even wifi location would be good enough for that!

**Comment by pikilipita** [comment] 2018-02-06 14:20
Great to hear, thanks!

I believe all ipads without sim card slots do not have GPS neither

**Comment by blairmacintyre** [comment] 2018-02-06 14:47
Question: are location services enable in the app for you?  Don't these iPads use wifi for location?

**Comment by blairmacintyre** [comment] 2018-02-06 14:49
Also, @pikilipita are you willing to test a new version via Testflight if we try to fix this?

**Comment by pikilipita** [comment] 2018-02-06 14:55
I can't see any location services in my iPad ( model 2017 - ios 11.2.5 ) settings. 
If it does exist, it's very well hidden.

That would be awesome to get a testflight version, you can send an invite to 
c_at_lune.xyz

**Comment by blairmacintyre** [comment] 2018-02-06 16:46
Go to the WebXR Viewer application preferences in Settings, the first preference should be "Location".

**Comment by pikilipita** [comment] 2018-02-07 08:36
The location setting of the app is greyed ( disabled ).
 I cannot choose anything else than 'never'

**Comment by blairmacintyre** [comment] 2018-02-07 13:19
Are location services turned off in Settings/Privacy?

**Comment by pikilipita** [comment] 2018-02-07 13:33
Sorry for all the trouble, I was not aware I had to look into settings > privacy to turn on location.
It works now, no more freeze, the 'people' example is working as expected

I can get back to my original post and suggest to display an error message when location is disabled / not available.

**Comment by blairmacintyre** [comment] 2018-02-07 13:55
We will start checking for that, yes.

**Comment by che1404** [comment] 2018-02-13 14:00
Hi @pikilipita thanks for reporting this issue. I cannot experience a camera freeze when I remove the location permissions from the iOS settings app. It just won't detect any plane. But no freeze.

**Comment by che1404** [comment] 2018-03-27 14:13
@blairmacintyre @pikilipita still cannot reproduce this issue. The app should work even if you don't grant GPS permissions.

**Comment by robomex** [comment] 2018-11-29 16:44
I attempted to replicate this issue using an iPad with combinations of Location Services on/off & permissions granted/denied and was unable to replicate the freeze using current code.  Marking as resolved.

**Closed by robomex** 2018-11-29 16:44 UTC
Labels: 2nd priority issues, bug
